/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#181d26',
        'primary-active': '#0d1218',
        ink: '#181d26',
        body: '#333840',
        muted: '#41454d',
        hairline: '#dddddd',
        'border-strong': '#9297a0',
        canvas: '#ffffff',
        'surface-soft': '#f8fafc',
        'surface-strong': '#e0e2e6',
        'surface-dark': '#181d26',
        'surface-dark-elevated': '#1d1f25',
        'signature-coral': '#aa2d00',
        'signature-forest': '#0a2e0e',
        'signature-cream': '#f5e9d4',
        'signature-peach': '#fcab79',
        'signature-mint': '#a8d8c4',
        'signature-yellow': '#f4d35e',
        'signature-mustard': '#d9a441',
        'on-primary': '#ffffff',
        'on-dark': '#ffffff',
        link: '#1b61c9',
        'link-active': '#1a3866',
        info: '#254fad',
        'info-border': '#458fff',
        success: '#006400',
        'success-border': '#39bf45',
        'pricing-ink': '#1d1f25',
      },
      fontFamily: {
        haas: [
          'Haas Grotesk',
          'Inter',
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI"',
          'Roboto',
          'Oxygen',
          'Ubuntu',
          'Cantarell',
          '"Fira Sans"',
          '"Droid Sans"',
          '"Helvetica Neue"',
          'sans-serif',
        ],
        'haas-disp': [
          'Haas Groot Disp',
          'Inter',
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI"',
          'sans-serif',
        ],
        'inter-display': ['Inter Display', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-xl': ['48px', { lineHeight: '1.1', letterSpacing: '0' }],
        'display-lg': ['40px', { lineHeight: '1.2', letterSpacing: '0' }],
        'display-md': ['32px', { lineHeight: '1.2', letterSpacing: '0' }],
        'title-lg': ['24px', { lineHeight: '1.35', letterSpacing: '0.12px' }],
        'title-md': ['20px', { lineHeight: '1.5', letterSpacing: '0' }],
        'title-sm': ['18px', { lineHeight: '1.4', letterSpacing: '0' }],
        'label-md': ['16px', { lineHeight: '1.4', letterSpacing: '0' }],
        button: ['16px', { lineHeight: '1.4', letterSpacing: '0' }],
        'body-md': ['14px', { lineHeight: '1.25', letterSpacing: '0' }],
        caption: ['14px', { lineHeight: '1.35', letterSpacing: '0.16px' }],
        legal: ['13.12px', { lineHeight: '1.2', letterSpacing: '0' }],
        'pricing-display': ['44.8px', { lineHeight: '1.1', letterSpacing: '0' }],
        'pricing-section': ['28px', { lineHeight: '1.2', letterSpacing: '0' }],
        'pricing-card-title': ['20px', { lineHeight: '1.3', letterSpacing: '0' }],
      },
      borderRadius: {
        xs: '2px',
        sm: '6px',
        md: '10px',
        lg: '12px',
        pill: '9999px',
      },
      spacing: {
        xxs: '4px',
        xs: '8px',
        sm: '12px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        xxl: '48px',
        section: '96px',
      },
      maxWidth: {
        content: '1280px',
      },
    },
  },
  plugins: [],
};
